server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/jizheping?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    druid:
      initial-size: 1 #初始化连接数
      min-idle: 1  #最小空闲连接数
      max-active: 1   #最大活动连接数
      test-on-borrow: true   #获取连接是测试是否可以使用
      stat-view-servlet.allow: true
  mvc:
    static-path-pattern: /**
mybatis:
  type-aliases-package: com.jizheping.entity
  mapper-locations: classpath:mapper/*Mapper.xml